setup file added

diff --git a/cloudupload b/cloudupload
--- a/cloudupload
+++ b/cloudupload
@@ -28,12 +28,23 @@ uploadfile(){
     container="uploads"
     #container=$ctr
     accountKey=$(az storage account keys list --resource-group $resourceGroup --account-name $storageAccount --query "[0].value" -o tsv)
-    az storage blob upload-batch 
-    --pattern "$1" 
-    --source . 
-    --destination $container 
-    --account-key $accountKey 
-    --account-name $storageAccount > /dev/null
+    #check_blob
+    flag=0
+    blobs_json=$(az storage blob list --account-name $storageAccount --account-key $accountKey --container-name $container -o json)
+    blob_names=($(echo $blobs_json | jq -r '.[].name'))
+    for blob in "${blob_names[@]}"; do
+        if [ "$blob" == "$1" ]; then
+            echo "ERROR:A blob with the name $blob already exists in $container"
+        flag=1
+        break
+        fi
+    done
+    if [ $flag -eq 0 ]; 
+    then
+        az storage blob upload-batch --pattern "$1" --source . --destination $container --account-key $accountKey --account-name $storageAccount > /dev/null 2>&1
+        return 0
+    fi
+    return -1
 }
 
 progressBar(){
@@ -64,13 +75,18 @@ then
         echo"'$path' is blocking access."
     elif [[  res  -eq 2 ]];
     then
-        echo "ERROR: '$1' is not readable."
+        echo "ERROR: $1 is not readable."
     else
-        echo "uploading $file to blob....."
-        #uploadfile $file
-        progressBar
-        echo "File uploaded successfully!!!"
+        echo "uploading $file to uploads....."
+        uploadfile $file
+        temp=$?
+        if [[ temp -eq 0 ]];
+        then
+            echo "File uploaded successfully :>"
+        else
+            echo "File upload unsuccessful :<"
+        fi
     fi
 else
-    echo " $file doesnot exists"
+    echo " ERROR: $file doesnot exists"
 fi
